# Basic settings
SEED: 0
RUN_NAME:
DEBUG: false

# Model configuration
MODEL:
  TYPE: mscan
  ENCODER:
    WEIGHTS:
  POSE_HEAD:
    SUPERVISE: true # We continue with pose supervision in stage 3
    USE_PINV: false
    CUT_BORDERS: true

# Training configuration
TRAINING:
  BATCH_SIZE: 8 # Keep the same batch size as stage 2
  NUM_WORKERS: 4
  EPOCHS: 20
  OPTIMIZER: adamw
  LR: 1e-5
  LR_SCHEDULER:
    TYPE: none
    MAX_LR: 1e-4
    PCT_START: 0.3
    ANNEAL_STRATEGY: cos
    CYCLE_MOMENTUM: true
    BASE_MOMENTUM: 0.85
    MAX_MOMENTUM: 0.95
    DIV_FACTOR: 25.0
    FINAL_DIV_FACTOR: 10000.0
    THREE_PHASE: false

  MIXED_PRECISION: bf16
  ROT_LOSS_WEIGHT: 1.0
  TRANS_LOSS_WEIGHT: 10.0
  POSE_LOSS_WEIGHT: 1000.0
  FLOW_LOSS_WEIGHT: 1e-4 # Regularization weight for the flow predictions
  DEPTH_LOSS_WEIGHT: 1e-3 # Regularization weight for the depth predictions
  POSE_ONLY: true # We don't have access to true flow and depths in stage 3...
  USE_PSEUDO_GT: true # ...so we use pseudo ground-truth labels to regularize the flow and depth predictions

  VAL_FIRST: false
  VAL_INTERVAL: 1

  CHECKPOINT:
    SAVE: true
    RESUME_PATH: # In stage 3 we resume from the last checkpoint of stage 2
    DIR: # Path to the directory to save checkpoints
    INTERVAL: 5
    OVERWRITE: false

# Dataset configuration
DATASET:
  TRAIN_DATA: # Path to the real-world finetuning training data csv file
  VAL_DATA: # Path to the real-world finetuning validation data csv file
  HEIGHT: 252
  WIDTH: 336
  CENTERCROP_DIMS: [224, 320]
  DATA_AUGMENT:
    - color_transforms
    - noise_transforms

# Logging configuration
LOGGING:
  PLATFORM: wandb # Options: wandb, null
  STEPS_PER_PRINT: 10  # How often to print training progress
  TRAIN_VISUALS_INTERVAL: 1000  # How often to log training visuals, in steps